name: Publish to Maven Central

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publishing Component 🚀
    runs-on: macos-latest
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v3.1.0

      - name: Setting up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Publishing to Central Sonatype
        run: |
          ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_ARMOR_KEY }}